name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      PANTHEON_KEY: ${{ secrets.PANTHEON_KEY }}
    strategy:
      matrix:
        python-version: [3.7, '3.10']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install tox tox-gh-actions

      - name: Run tox
        run: tox

      - name: Coverage report
        run: codecov